const test = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..`;

const reader = require('../../utils/inputReader');
const input = reader.getInputFromArgs(process.argv);

const { pathFinder } = require("./pathFinder");
const resp = pathFinder(input);

console.log('The answer is', resp);